-- Generated by Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   at:        2021-04-05 09:49:18 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE book (
    id_book      NUMBER(3) NOT NULL,
    title_book   VARCHAR2(50) NOT NULL,
    author_book  VARCHAR2(40) NOT NULL
);

ALTER TABLE book ADD CONSTRAINT book_pk PRIMARY KEY ( id_book );

CREATE TABLE client (
    id_client    NUMBER(3) NOT NULL,
    name_client  VARCHAR2(40) NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( id_client );

CREATE TABLE comicbook (
    id_comic      NUMBER(4) NOT NULL,
    series_comic  VARCHAR2(50) NOT NULL,
    number_comic  NUMBER(3)
);

ALTER TABLE comicbook ADD CONSTRAINT comicbook_pk PRIMARY KEY ( id_comic );

CREATE TABLE rental (
    id_rental           NUMBER(3) NOT NULL,
    rented_date         DATE,
    returned_date       DATE,
    book_id_book        NUMBER(3) ,
    comicbook_id_comic  NUMBER(4) ,
    client_id_client    NUMBER(3) 
);

CREATE UNIQUE INDEX rental__idx ON
    rental (
        book_id_book
    ASC );

CREATE UNIQUE INDEX rental__idxv1 ON
    rental (
        client_id_client
    ASC );

CREATE UNIQUE INDEX rental__idxv2 ON
    rental (
        comicbook_id_comic
    ASC );

ALTER TABLE rental ADD CONSTRAINT rental_pk PRIMARY KEY ( id_rental );

ALTER TABLE rental
    ADD CONSTRAINT rental_book_fk FOREIGN KEY ( book_id_book )
        REFERENCES book ( id_book );

ALTER TABLE rental
    ADD CONSTRAINT rental_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );

ALTER TABLE rental
    ADD CONSTRAINT rental_comicbook_fk FOREIGN KEY ( comicbook_id_comic )
        REFERENCES comicbook ( id_comic );

CREATE SEQUENCE book_id_book_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER book_id_book_trg BEFORE
    INSERT ON book
    FOR EACH ROW
    WHEN ( new.id_book IS NULL )
BEGIN
    :new.id_book := book_id_book_seq.nextval;
END;
/

CREATE SEQUENCE client_id_client_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER client_id_client_trg BEFORE
    INSERT ON client
    FOR EACH ROW
    WHEN ( new.id_client IS NULL )
BEGIN
    :new.id_client := client_id_client_seq.nextval;
END;
/

CREATE SEQUENCE comicbook_id_comic_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER comicbook_id_comic_trg BEFORE
    INSERT ON comicbook
    FOR EACH ROW
    WHEN ( new.id_comic IS NULL )
BEGIN
    :new.id_comic := comicbook_id_comic_seq.nextval;
END;
/

CREATE SEQUENCE rental_id_rental_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER rental_id_rental_trg BEFORE
    INSERT ON rental
    FOR EACH ROW
    WHEN ( new.id_rental IS NULL )
BEGIN
    :new.id_rental := rental_id_rental_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             3
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
